### PR TITLE
Update with EESSI_SSH_KEYS support.

### PR DESCRIPTION
**Pull request by terjekv**

### CODE REVIEW

**Review by bedroge — CHANGES_REQUESTED** [review]
I don't really understand this sentence and what value that variable should get? All public keys that should have access to the account?

**Comment by terjekv** [comment]
You understood it correctly, yes. :)

**Comment by bedroge** [comment]
And with multiple ones, that would be something like `EESSI_SSH_KEYS="ssh-rsa blablabla somename\nssh-ed25519 blabla someothername\n....etc..."`?

**Comment by terjekv** [comment]
Proper line breaks are good:
```
EESSI_SSH_KEYS="ssh-rsa blabla terje
ssh-rsa foofoo bob
ssh-ed25519 modernity ashurbanipal"
```
Probably worth documenting. :)

**Review by bedroge — APPROVED** [review]

**Pull request merged**
